Repository future-code-lab/botnet, pull requests merged in 2021-07, with the labels that each got.

#28 Addition dialog bot
  development/bot/adapter.py
  development/bot/bot.py
  development/bot/server.py
Labels: backend

#26 BS - Docker
  .github/labeler.yml
  .github/workflows/python-package.yml
  development/.gitignore
  development/Dockerfile
  development/Pipfile
  development/docker-compose.yml
  development/requirements.txt
Labels: backend, ci/cd, ready to merge, ready to review

#30 BS - Bot
  development/bot/bot.py
  development/bot/server.py
Labels: backend, ready to review
