Repository future-code-lab/botnet, pull requests merged in 2021-10, with the labels that each got.

#39 BS - Bot
  development/bot/.env
  development/bot/README.md
  development/bot/base/__init__.py
  development/bot/base/bot.py
  development/bot/base/prepare_message.py
  development/bot/base/server.py
  development/bot/base/settings.py
  development/bot/telegram.py
  development/bot/tests.py
  development/bot/vk.py
Labels: backend

#44 DS-43: Card component
  development/components/.storybook/preview-head.html
  development/components/public/background.png
  development/components/public/fonts/Inter-Bold.ttf
  development/components/public/fonts/Inter-Regular.ttf
  development/components/public/fonts/Montserrat-Bold.ttf
  development/components/public/fonts/Montserrat-Regular.ttf
  development/components/public/global.css
  development/components/public/index.html
  development/components/src/components/Button/Button.module.scss
  development/components/src/components/Button/Button.tsx
  development/components/src/components/Button/PrimaryButton.tsx
  development/components/src/components/Button/SecondaryButton.tsx
  development/components/src/components/Card/Card.module.scss
  development/components/src/components/Card/Card.test.tsx
  development/components/src/components/Card/Card.tsx
  development/components/src/components/Card/__snapshots__/Card.test.tsx.snap
  development/components/src/components/Card/fixture.tsx
  development/components/src/components/Card/index.ts
  development/components/src/components/Card/stories/Card.stories.tsx
  development/components/src/components/Container/Container.test.tsx
  development/components/src/components/Container/Container.tsx
  development/components/src/components/Container/__snapshots__/Container.test.tsx.snap
  development/components/src/components/Container/fixture.tsx
  development/components/src/components/Header/Header.test.tsx
  development/components/src/components/Header/Header.tsx
  development/components/src/components/Header/Header.types.ts
  development/components/src/components/Header/HeaderTag.tsx
  development/components/src/components/Header/__snapshots__/Header.test.tsx.snap
  development/components/src/components/Header/fixture.tsx
  development/components/src/components/Header/index.ts
  development/components/src/components/Notification/ErrorNotification.tsx
  development/components/src/components/Notification/Notification.tsx
  development/components/src/components/Notification/SuccessNotification.tsx
Labels: documentation, frontend, storybook

#51 docs: addition of basic chapters into structure for components
  development/components/README.md
Labels: documentation, frontend, ready to review

#54 DS/components-tag
  development/components/.releaserc
  development/components/src/components/Card/stories/Card.stories.tsx
  development/components/src/components/Notification/Notification.module.scss
  development/components/src/components/Tag/Tag.module.scss
  development/components/src/components/Tag/Tag.test.tsx
  development/components/src/components/Tag/Tag.tsx
  development/components/src/components/Tag/__snapshots__/Tag.test.tsx.snap
  development/components/src/components/Tag/fixture.ts
  development/components/src/components/Tag/index.ts
  development/components/src/components/Tag/stories/RoundTag.stories.tsx
  development/components/src/components/Tag/stories/Tag.stories.tsx
  development/components/src/components/Tag/stories/Tags.stories.tsx
Labels: ci/cd, frontend, ready to review, storybook
